default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black

ci:
    autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
